config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :questions do
    collection do
      post :sort
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.order(:position)
  end

  def sort
    params[:question].each_with_index do |id, index|
      Question.where(id: id).update_all(position: index + 1)
    end

    head :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/questions/index.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <h2> Questions </h2>
    <div id="questions" class="list-group" data-url="<%= sort_questions_path %>">
      <% @questions.each do |question| %>
        <%= link_to "#{question.id} #{question.content}", question, class: "list-group-item", id: dom_id(question) %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>